"""Regenerate the paper's synthetic evidence, never observations from Erlangen.

Run from the repository root: python -m paper.generate_example
Existing targets are never overwritten; use --output for a separate review run.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
from pathlib import Path
from tempfile import TemporaryDirectory

from matplotlib import rc_context
from matplotlib.backends.backend_agg import FigureCanvasAgg
from matplotlib.collections import LineCollection
from matplotlib.figure import Figure
from matplotlib.lines import Line2D
from matplotlib.ticker import MaxNLocator
from shapely.geometry import LineString
from shapely.ops import unary_union

from osm_accessibility import __version__
from osm_accessibility.demo import synthetic_dataset
from osm_accessibility.experiment import (
    implementation_fingerprint,
    load_run,
    run_experiment,
    scientific_fingerprint,
)
from osm_accessibility.models import Coordinate
from osm_accessibility.profiles import CostParameters, wheelchair_profile
from osm_accessibility.visualization import projected_positions

SOFTWARE_COMMIT = "b3d2076689725777b4581e36a5c9ce7d12c507ae"
IMPLEMENTATION_SHA256 = "f85fbe8d6a05801470d96cd46b946753d15af824c2d346dbf246c5586fb64e09"
CORE_SHA256 = "ef69ad5f613476c4e92a60e718a9cf564ac6c3cf9847c7947fd21bf2e36d6362"
OUTPUT_NAMES = ("synthetic-comparison.pdf", "example-table.tex", "example-provenance.json")


def _table(comparison: dict) -> str:
    selected, standard = comparison["selected"], comparison["standard"]
    rows = []
    for label, key, decimals in (
        ("Distance (m)", "distance_m", 1),
        (r"Recognised-data coverage (\%)", "coverage_percent", 1),
        ("Blocked directed traversals", "hard_block_violations", 0),
        ("Known soft-conflict groups", "conflict_count", 0),
        ("Unknown-observation groups", "unknown_count", 0),
    ):
        first, second = selected[key], standard[key]
        rows.append(f"{label} & {first:.{decimals}f} & {second:.{decimals}f} & "
                    f"{first - second:+.{decimals}f} " + r"\\")
    # An infeasible standard trace never receives a fabricated numeric score.
    if standard["hard_block_violations"]:
        rows.insert(1, f"Profile match (\\%) & {selected['score_percent']:.1f} & "
                    + r"\textit{Infeasible} & --- \\")
    else:
        raise ValueError("The paper's documented synthetic standard should be infeasible")
    for row in comparison["obstacle_rows"]:
        if row["selected"] or row["standard"]:
            rows.append(f"{row['label']} encounters & {row['selected']} & {row['standard']} & "
                        f"{row['difference']:+d} " + r"\\")
    return ("% Generated by paper/generate_example.py; do not hand-edit numeric results.\n"
            + r"\begin{tabular}{@{}lrrr@{}}" + "\n"
            + r"\toprule Measure & Selected & Standard & Change \\" + "\n"
            + "\\midrule\n" + "\n".join(rows)
            + "\n\\bottomrule\n\\end{tabular}\n")


def _plot(path: Path, graph, selected_route, standard_nodes: list[str], comparison: dict) -> None:
    """Plot actual fixture traces and assessment counts, with no external images."""
    positions = projected_positions(graph)
    selected_points = [positions[node] for node in selected_route.nodes]
    standard_points = [positions[node] for node in standard_nodes]
    # Same metric corridor principle as the application, a smaller paper-only radius.
    corridor = unary_union([LineString(points).buffer(60, quad_segs=64)
                            for points in (selected_points, standard_points)])
    segments = []
    for edge in graph.edges:
        clipped = LineString((positions[edge.source], positions[edge.target])).intersection(corridor)
        pieces = list(clipped.geoms) if clipped.geom_type == "MultiLineString" else [clipped]
        for piece in pieces:
            if not piece.is_empty and piece.geom_type == "LineString":
                segments.append(list(piece.coords))
    with rc_context({"font.family": "DejaVu Sans", "font.size": 9, "pdf.fonttype": 42,
                     "text.usetex": False}):
        figure = Figure(figsize=(7.1, 3.55), facecolor="white")
        FigureCanvasAgg(figure)
        geometry = figure.add_axes((.08, .22, .37, .61))
        bars = figure.add_axes((.73, .25, .24, .55))
        blue, orange = "#1464b4", "#df7c16"
        geometry.add_collection(LineCollection(segments, colors="#d0d5dc", linewidths=.8))
        geometry.plot(*zip(*selected_points), color="white", linewidth=4.8)
        geometry.plot(*zip(*selected_points), color=blue, linewidth=2.5)
        geometry.plot(*zip(*standard_points), color="white", linewidth=4.3, linestyle="--")
        geometry.plot(*zip(*standard_points), color=orange, linewidth=2.1, linestyle="--")
        for label, point, offset in (("Start", selected_points[0], (-23, -13)),
                                      ("End", selected_points[-1], (5, -13))):
            geometry.scatter(*point, s=27, facecolor="white", edgecolor="#182b49", zorder=5)
            geometry.annotate(label, point, xytext=offset, textcoords="offset points", fontsize=8)
        xmin, ymin, xmax, ymax = corridor.bounds
        geometry.set(xlim=(xmin, xmax), ylim=(ymin, ymax), xlabel="Easting (m)", ylabel="Northing (m)")
        geometry.set_aspect("equal", adjustable="box")
        geometry.xaxis.set_major_locator(MaxNLocator(4))
        geometry.yaxis.set_major_locator(MaxNLocator(4))
        geometry.set_title("(a) Exact synthetic route traces", fontsize=9)
        kinds = ["stairs", "wheelchair_restriction", "lighting"]
        labels = ["Stairway\nencounters", "Wheelchair\nrestrictions", "Unlit-way\nencounters"]
        first = [comparison["selected"]["obstacle_counts"][kind] for kind in kinds]
        second = [comparison["standard"]["obstacle_counts"][kind] for kind in kinds]
        for values, offset, color in ((first, -.18, blue), (second, .18, orange)):
            levels = [i + offset for i in range(len(kinds))]
            bars.barh(levels, values, height=.31, color=color)
            for level, value in zip(levels, values):
                bars.text(value + .05, level, str(value), va="center", fontsize=9, color=color)
        bars.set_yticks(range(len(kinds)), labels)
        bars.invert_yaxis()
        bars.set_xlim(0, 1.4)
        bars.set_xticks([0, 1])
        bars.set_xlabel("Grouped encounters")
        bars.set_title("(b) Common-profile assessment", fontsize=9, pad=16)
        for axis in (geometry, bars):
            axis.tick_params(labelsize=8)
            axis.spines["top"].set_visible(False)
            axis.spines["right"].set_visible(False)
        figure.suptitle("Synthetic fixture -- not observed OpenStreetMap conditions", fontsize=10, y=.98)
        figure.legend(handles=[Line2D([], [], color=blue, linewidth=2.5, label="Selected wheelchair profile"),
                                Line2D([], [], color=orange, linewidth=2.1, linestyle="--",
                                       label="No-preference standard (infeasible)")],
                      loc="lower center", bbox_to_anchor=(.5, .01), ncols=2, frameon=False, fontsize=8.5)
        with path.open("xb") as stream:
            figure.savefig(stream, format="pdf", bbox_inches="tight", metadata={
                "Title": "Synthetic paired-route illustration",
                "Creator": "paper/generate_example.py using osm-accessibility-research 0.3.0",
                "CreationDate": None, "ModDate": None,
            })
        figure.clear()


def generate(output: Path) -> dict:
    if __version__ != "0.3.0" or implementation_fingerprint() != IMPLEMENTATION_SHA256:
        raise ValueError("Run with the unchanged 0.3.0 code documented at " + SOFTWARE_COMMIT)
    if scientific_fingerprint() != CORE_SHA256:
        raise ValueError("The scientific core differs from the manuscript's reference version")
    if any((output / name).exists() or (output / name).is_symlink() for name in OUTPUT_NAMES):
        raise FileExistsError("Paper evidence exists; select a new --output directory for regeneration")
    with TemporaryDirectory(prefix="softwarex-example-") as temporary:
        run_dir = Path(temporary) / "run"
        manifest = run_experiment(
            synthetic_dataset(), Coordinate(49.58, 11), Coordinate(49.58, 11.002),
            wheelchair_profile(), CostParameters(accessibility_factor=6), run_dir, plots=False,
        )
        _, graph, route, _, _ = load_run(run_dir)
        comparison = manifest["presentation"]["comparison"]
        if (route.nodes != ("s", "smooth_a", "smooth_b", "smooth_c", "t")
                or manifest["standard_route"]["route"]["node_ids"] != ["s", "stairs_mid", "t"]
                or not math.isclose(route.distance_m, 477.77540549813034, abs_tol=1e-8)
                or not math.isclose(comparison["selected"]["score_percent"], 97.60044690727466, abs_tol=1e-8)):
            raise ValueError("Synthetic results no longer match the numerical manuscript statements")
        output.mkdir(parents=True, exist_ok=True)
        _plot(output / OUTPUT_NAMES[0], graph, route, manifest["standard_route"]["route"]["node_ids"], comparison)
        with (output / OUTPUT_NAMES[1]).open("x", encoding="utf-8", newline="\n") as stream:
            stream.write(_table(comparison))
        evidence = {
            "synthetic": True, "verified_software_commit": SOFTWARE_COMMIT,
            "implementation_sha256": IMPLEMENTATION_SHA256, "scientific_sha256": CORE_SHA256,
            "software_version": __version__, "model_version": manifest["model_version"],
            "dataset": manifest["dataset"], "graph_counts": manifest["graph_counts"],
            "graph_sha256": manifest["graph_sha256"], "profile": manifest["profile"],
            "cost_parameters": manifest["cost_parameters"],
            "selected_route": manifest["route"], "standard_route": manifest["standard_route"],
            "comparison": comparison, "baselines": manifest["baselines"],
            "runtime": {key: manifest["environment"][key] for key in ("python", "platform", "dependencies")},
            "figure_corridor_radius_m": 60,
            "artifact_sha256": {name: hashlib.sha256((output / name).read_bytes()).hexdigest()
                                for name in OUTPUT_NAMES[:2]},
            "note": "Deterministic synthetic fixture; no Erlangen extract or field observations used.",
        }
        with (output / OUTPUT_NAMES[2]).open("x", encoding="utf-8") as stream:
            json.dump(evidence, stream, indent=2, ensure_ascii=False, allow_nan=False)
            stream.write("\n")
    return evidence


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=Path(__file__).parent / "figures")
    args = parser.parse_args()
    evidence = generate(args.output)
    print(f"Wrote {len(OUTPUT_NAMES)} paper assets to {args.output}")
    print(f"Verified software {evidence['software_version']} at {SOFTWARE_COMMIT}; synthetic data only.")


if __name__ == "__main__":
    main()